kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: java:8
  SourceLocation: https://github.com/NicoFunes/ApiNico
  Ref: HEAD
  SourceType: git
  Ports:
  - 8080/TCP
  - 8443/TCP
  - 8778/TCP
  Application: laapi
  Project: fuselab
  Name: componentedemierda
